# Use the official bun image as base
FROM imbios/bun-node:latest

 # Set the working directory
WORKDIR /frontend

 

# Copy the package.json file into the container
COPY package.json /frontend/package.json
# Install dependencies
RUN bun install

COPY entrypoint.sh /frontend/entrypoint.sh
RUN chmod +x /frontend/entrypoint.sh
CMD ["/bin/bash", "/frontend/entrypoint.sh"]
 
 