# Use the official bun image as base
FROM oven/bun:1-debian

# Set the working directory
WORKDIR /frontend
 

# Copy the package.json file into the container
COPY package.json /frontend/package.json
# Install dependencies
RUN bun install


CMD ["bun", "run", "dev"]