version: '3.9'
services:
  pythonbackend:
    container_name: pythonbackend
    build:
      context: ./backend/python/
      dockerfile: dockerfile.CPU 
    restart: unless-stopped
    volumes:
      - ./:/pythonbackend
    ports:
      - '8000:8000'
    networks:
      - yasminenet

  cppbackend:
    container_name: cppbackend
    build:
      context: ./backend/c++/
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/cppbackend
    ports:
      - '8080:8080'
    networks:
      - yasminenet
 

  browserfrontend:
    container_name: browserfrontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/frontend
 
    ports:
      - '3001:3001'
    networks:
      - yasminenet

networks:
  yasminenet:

