FROM rust:alpine AS builder
 
# If there's a specific static package, install it. Replace `libressl-static` with the actual package if different.
 
RUN apk add libressl-dev
RUN apk add build-base
RUN rustup target add x86_64-unknown-linux-musl


ENV USER=myip
ENV UID=10001

RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"

WORKDIR /rustapp
# Copy only the manifest files first and build dependencies
COPY ./Cargo.toml ./Cargo.lock ./
# Then copy the source code
COPY ./src ./src

RUN cargo build --release --target x86_64-unknown-linux-musl
FROM rust:alpine
WORKDIR /rustapp

# Import from builder
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group

# Copy our build
COPY --from=builder /rustapp/target/x86_64-unknown-linux-musl/release/rust-docker-web /rustapp/rust-docker-web
RUN chmod +x /rustapp/rust-docker-web
# Use an unprivileged user
USER myip:myip
#make executable

CMD ["/rustapp/rust-docker-web"]
