########################################################################################################################
# simplehttpserver build stage
########################################################################################################################

FROM alpine:latest AS build

RUN apk update && \
    apk add --no-cache \
    build-base \
    cmake \
    boost boost-dev 

WORKDIR /simplehttpserver

COPY src/ ./src/
COPY CMakeLists.txt .

WORKDIR /simplehttpserver/build

RUN cmake -DCMAKE_BUILD_TYPE=Release .. && \
    cmake --build . --parallel 8

########################################################################################################################
# simplehttpserver image
########################################################################################################################

FROM alpine:latest

RUN apk update && \
    apk add --no-cache \
    libstdc++ \
    boost boost-dev 

RUN addgroup -S shs && adduser -S shs -G shs
USER shs

COPY --chown=shs:shs --from=build \
    ./simplehttpserver/build/src/simplehttpserver \
    ./app/

 
ENTRYPOINT [ "./app/simplehttpserver" ]