name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Execute SSH commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
       
        script: |
          cd /home/dev/Yasmineoss/yasmineoss/
          git stash --include-untracked         
          # Stash all changes (including untracked)
          git pull --rebase                       # Pull with rebase
          docker compose -f dockercomposeCPU.yml down
          docker compose -f dockercomposeCPU.yml up --build -d
